// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tblBoletasAportesEspeciales_BoletaPagada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblBoletasAportesEspeciales_BoletaPagada));
        
        string IMigrationMetadata.Id
        {
            get { return "202006021343051_tblBoletasAportesEspeciales_BoletaPagada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
