// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tblBoletaAportesEspecial_CamposEmpresa_NoRequeridos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblBoletaAportesEspecial_CamposEmpresa_NoRequeridos));
        
        string IMigrationMetadata.Id
        {
            get { return "202006021519451_tblBoletaAportesEspecial_CamposEmpresa_NoRequeridos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
