// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tblBoletas_cantEmpleados_Aportes2_cantAfiliados_aportes5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblBoletas_cantEmpleados_Aportes2_cantAfiliados_aportes5));
        
        string IMigrationMetadata.Id
        {
            get { return "202006101613455_tblBoletas_cantEmpleados_Aportes2_cantAfiliados_aportes5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
